# Change these first
owner: shopstarco # Your GitHub organization or username, where this repository lives
repo: shopstatus # The name of this repository

sites:
  - name: Shopstar Platform
    url: https://app.shopstar.co.za
  - name: Shopstar CDN
    url: https://cdn2.shopstar.co.za/DevnnSl7qd2utisbU05pMugSOw3yH-pE1TMA91CIlgc/rs:fill:540:540:1/plain/https://assets.shopstar.co.za/uploads/product_image/product_image/display_a5403f09-ec11-4e0f-b5b3-c42a9b682d52.jpg
  - name: Shopstar API
    url: https://api.shopstar.co.za/

assignees:
  - chriscapetown

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.shopstar.co.za
  # baseUrl: /shopstatus
  logoUrl: https://uploads-ssl.webflow.com/62301d8bb02c26d9e0817825/62fa2edfc55f63e35930ae99_vetor%20hero.svg
  name: Shopstar Service Status
  introTitle: "Shopstar Service Status Dashboard"
  introMessage: "Welcome to the service status dashboard. If something is not working for you - you can check on our automatic service status reports below."
  navbar:
    - title: Status
      href: /
    - title: Support
      href: https://support.shopstar.co.za
